Layout/LineLength:
  Max: 99
Metrics/BlockLength:
  Max: 100
Metrics/MethodLength:
  Max: 20
Style/HashSyntax:
  Enabled: false
Style/FormatStringToken:
  Enabled: false
Style/HashEachMethods:
  Enabled: true
Style/HashTransformKeys:
  Enabled: true
Style/HashTransformValues:
  Enabled: true

